### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#357] opened 2015-12-14 23:25 UTC
protocol.version: 1
os.name: Windows 7
java.version: 1.8.0_51
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-143.381
app.version.major: 15
app.version.minor: 0
app.build.date: 1446134400000
app.build.date.release: 1446393600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.02
last.action: ShowProjectStructureSettings
previous.exception: null
assignee.id: null

```
java.lang.NullPointerException
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:90)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:77)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:60)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:75)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:45)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:240)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox$1.setItem(XDebuggerExpressionComboBox.java:100)
	at com.intellij.openapi.ui.ComboBox$MyEditor.setItem(ComboBox.java:376)
	at javax.swing.JComboBox.configureEditor(JComboBox.java:1404)
	at javax.swing.plaf.basic.BasicComboBoxUI.configureEditor(BasicComboBoxUI.java:787)
	at javax.swing.plaf.basic.BasicComboBoxUI.addEditor(BasicComboBoxUI.java:736)
	at javax.swing.plaf.basic.BasicComboBoxUI$Handler.propertyChange(BasicComboBoxUI.java:1710)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8422)
	at javax.swing.JComboBox.setEditor(JComboBox.java:506)
	at com.intellij.openapi.ui.ComboBox.setEditor(ComboBox.java:259)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.b(XDebuggerExpressionComboBox.java:110)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.<init>(XDebuggerExpressionComboBox.java:56)
	at com.intellij.xdebugger.impl.breakpoints.ui.XBreakpointActionsPanel.init(XBreakpointActionsPanel.java:62)
	at com.intellij.xdebugger.impl.breakpoints.ui.XLightBreakpointPropertiesPanel.<init>(XLightBreakpointPropertiesPanel.java:132)
	at com.intellij.xdebugger.impl.ui.DebuggerUIUtil.showXBreakpointEditorBalloon(DebuggerUIUtil.java:187)
	at com.intellij.xdebugger.impl.actions.XDebuggerEditBreakpointActionHandler.doShowPopup(XDebuggerEditBreakpointActionHandler.java:37)
	at com.intellij.xdebugger.impl.actions.EditBreakpointActionHandler.editBreakpoint(EditBreakpointActionHandler.java:61)
	at com.intellij.xdebugger.impl.actions.EditBreakpointAction$ContextAction.actionPerformed(EditBreakpointAction.java:52)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.a(EditorGutterComponentImpl.java:1506)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.e(EditorGutterComponentImpl.java:1668)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.mouseReleased(EditorGutterComponentImpl.java:1461)
	at com.intellij.openapi.editor.impl.EditorImpl.a(EditorImpl.java:4263)
	at com.intellij.openapi.editor.impl.EditorImpl.access$12600(EditorImpl.java:124)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter$2.run(EditorImpl.java:5835)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.c(EditorImpl.java:5839)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:5725)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

```
null
```

**Comment by JesusFreke** [comment] 2016-02-15 00:42
Duplicate of #362

**Closed by JesusFreke** 2016-02-15 00:42 UTC
