### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#308] opened 2015-09-24 13:13 UTC
protocol.version: 1
os.name: Linux
java.version: 1.8.0_45
java.vm.vendor: Oracle Corporation
app.name: Studio
app.name.full: Android Studio
app.name.version: Android Studio
app.eap: false
app.internal: false
app.build: AI-141.1903250
app.version.major: 1
app.version.minor: 2
app.build.date: 1430758800000
app.build.date.release: 1430758800000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.02
last.action: Debug
previous.exception: null
assignee.id: null

```
java.lang.NullPointerException
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:90)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:77)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:60)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:75)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:45)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:228)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox$1.setItem(XDebuggerExpressionComboBox.java:100)
	at com.intellij.openapi.ui.ComboBox$MyEditor.setItem(ComboBox.java:375)
	at javax.swing.JComboBox.configureEditor(JComboBox.java:1404)
	at javax.swing.plaf.basic.BasicComboBoxUI.configureEditor(BasicComboBoxUI.java:787)
	at javax.swing.plaf.basic.BasicComboBoxUI.addEditor(BasicComboBoxUI.java:736)
	at javax.swing.plaf.basic.BasicComboBoxUI$Handler.propertyChange(BasicComboBoxUI.java:1710)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8422)
	at javax.swing.JComboBox.setEditor(JComboBox.java:506)
	at com.intellij.openapi.ui.ComboBox.setEditor(ComboBox.java:258)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.initEditor(XDebuggerExpressionComboBox.java:109)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.<init>(XDebuggerExpressionComboBox.java:56)
	at com.intellij.xdebugger.impl.breakpoints.ui.XBreakpointActionsPanel.init(XBreakpointActionsPanel.java:61)
	at com.intellij.xdebugger.impl.breakpoints.ui.XLightBreakpointPropertiesPanel.<init>(XLightBreakpointPropertiesPanel.java:121)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointItem.doUpdateDetailView(XBreakpointItem.java:106)
	at com.intellij.ui.popup.util.ItemWrapper.updateDetailView(ItemWrapper.java:40)
	at com.intellij.ui.popup.util.DetailController.doUpdateDetailViewWithItem(DetailController.java:36)
	at com.intellij.ui.popup.util.DetailController$1.run(DetailController.java:84)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

```
null
```

**Comment by JesusFreke** [comment] 2016-02-27 21:27
Duplicate of #362

**Closed by JesusFreke** 2016-02-27 21:27 UTC
Labels: smalidea
