### ISSUE TITLE
Android L deodex. The last instruction in the method is truncated

### ISSUE THREAD

**Issue by ap0stol** [JesusFreke/smali#287] opened 2015-04-24 04:10 UTC
Can't deodex some app from Xperia Z2 5.0.2 using latest baksmali\smali

C:\sony\oat2dex>oat2dex.bat Exchange2.odex
OAT2DEX : Version 0.1 By SOFTDX

OAT Hader Checking.. : OK!
DEX Hader Checking.. : OK!

C:\sony\oat2dex>oat2dex.bat Exchange2.odex temp.dex
OAT2DEX : Version 0.1 By SOFTDX

OAT Hader Checking.. : OK!
DEX Hader Checking.. : OK!
Plase Wait.. temp.dex DEX File Create..
DEX temp.dex Files Create End.

C:\sony\oat2dex>java -jar baksmali-2.0.5-17828564.jar -a 21 -x temp.dex -o deodex
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.jf.util.ExceptionWithContext: The last instruction in the method is truncated
        at org.jf.baksmali.baksmali.disassembleDexFile(baksmali.java:166)
        at org.jf.baksmali.main.main(main.java:290)
Caused by: java.util.concurrent.ExecutionException: org.jf.util.ExceptionWithContext: The last instruction in the method is truncated
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.jf.baksmali.baksmali.disassembleDexFile(baksmali.java:160)
        ... 1 more
Caused by: org.jf.util.ExceptionWithContext: The last instruction in the method is truncated
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:87)
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:75)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at org.jf.baksmali.Adaptors.ClassDefinition.findFieldsSetInStaticConstructor(ClassDefinition.java:73)
        at org.jf.baksmali.Adaptors.ClassDefinition.<init>(ClassDefinition.java:58)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:198)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Old version work good, but i have crashes of some apps on device

baksmali-2.0.5-17828564.jar https://drive.google.com/file/d/0B_Pm8e5HGcypRUo3ajA4Y0RTYWs/view?usp=sharing
Exchange2.odex https://drive.google.com/file/d/0B_Pm8e5HGcypLWZ2aFV1eDY5dWc/view?usp=sharing

**Comment by JesusFreke** [comment] 2015-04-24 04:14
Duplicate of issue 269. Deodexing art files is not currently supported. Deodexing 5.0 and 5.1 odex files will never be supported, but the next major version will be supported.

**Closed by JesusFreke** 2015-04-24 04:14 UTC

**Comment by marckevinflores** [comment] 2017-03-01 00:44
Mr. JesusFreke can you help me how to solve this problem to Kitkat 4.4.2
Error occurred while disassembling class Lcom.android.server.accessibility.AccessibilityManagerService; - skipping class
java.lang.RuntimeException: Invalid method index: 35
    at org.jf.dexlib2.analysis.InlineMethodResolver$InlineMethodResolver_version36.resolveExecuteInline(InlineMethodResolver.java:175)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeExecuteInline(MethodAnalyzer.java:1422)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:941)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:202)
    at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:137)
    at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:387)
    at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:296)
    at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:198)
    at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:322)
    at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
    at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:220)
    at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
    at org.jf.baksmali.baksmali$1.call(baksmali.java:144)
    at org.jf.baksmali.baksmali$1.call(baksmali.java:142)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)


Error occurred while disassembling class Lcom.android.server.accessibility.TouchExplorer$InjectedPointerTracker; - skipping class
java.lang.RuntimeException: Invalid method index: 36
    at org.jf.dexlib2.analysis.InlineMethodResolver$InlineMethodResolver_version36.resolveExecuteInline

Can't decompile services.odex :(

**Comment by JesusFreke** [comment] 2017-03-01 00:48
Please file a new issue. Don't comment on an unrelated issue that is already closed.
