### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#300] opened 2015-08-30 12:11 UTC
protocol.version: 1
os.name: Linux
java.version: 1.8.0_45
java.vm.vendor: Oracle Corporation
app.name: Studio
app.name.full: Android Studio
app.name.version: Android Studio
app.eap: false
app.internal: false
app.build: AI-141.2178183
app.version.major: 1
app.version.minor: 3
app.build.date: 1439917200000
app.build.date.release: 1439917200000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.02
last.action: EditorUp
previous.exception: null
assignee.id: null

```
java.lang.NullPointerException
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.isContextAccepted(SmaliCodeFragmentFactory.java:72)
	at com.intellij.debugger.impl.DebuggerUtilsEx.getCodeFragmentFactories(DebuggerUtilsEx.java:90)
	at com.intellij.debugger.impl.DebuggerUtilsEx$2.compute(DebuggerUtilsEx.java:461)
	at com.intellij.debugger.impl.DebuggerUtilsEx$2.compute(DebuggerUtilsEx.java:457)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.debugger.impl.DebuggerUtilsEx.findAppropriateCodeFragmentFactory(DebuggerUtilsEx.java:457)
	at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor$1.compute(EvaluationDescriptor.java:85)
	at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor$1.compute(EvaluationDescriptor.java:82)
	at com.intellij.debugger.DebuggerInvocationUtil$3.compute(DebuggerInvocationUtil.java:76)
	at com.intellij.psi.impl.PsiDocumentManagerBase$6.run(PsiDocumentManagerBase.java:390)
	at com.intellij.psi.impl.PsiDocumentManagerBase$7.run(PsiDocumentManagerBase.java:422)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:417)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:387)
	at com.intellij.debugger.DebuggerInvocationUtil.commitAndRunReadAction(DebuggerInvocationUtil.java:72)
	at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor.calcValue(EvaluationDescriptor.java:82)
	at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.setContext(ValueDescriptorImpl.java:188)
	at com.intellij.debugger.engine.JavaDebuggerEvaluator$1.threadAction(JavaDebuggerEvaluator.java:89)
	at com.intellij.debugger.engine.events.DebuggerContextCommandImpl.contextAction(DebuggerContextCommandImpl.java:59)
	at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

```

```
null
```

**Comment by JesusFreke** [comment] 2016-02-27 21:28
Duplicate of #368

**Closed by JesusFreke** 2016-02-27 21:28 UTC
Labels: smalidea
