### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#360] opened 2015-12-25 04:39 UTC
protocol.version: 1
os.name: Windows 8
java.version: 1.8.0_51
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-143.381
app.version.major: 15
app.version.minor: 0
app.build.date: 1446134400000
app.build.date.release: 1446393600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.02
last.action: EvaluateExpression
previous.exception: null
assignee.id: null

```
java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:504)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:496)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:479)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:134)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:323)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:93)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:77)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:60)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:75)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:45)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:240)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionEditor.<init>(XDebuggerExpressionEditor.java:56)
	at com.intellij.xdebugger.impl.evaluate.ExpressionInputComponent.<init>(ExpressionInputComponent.java:62)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.b(XDebuggerEvaluationDialog.java:257)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.a(XDebuggerEvaluationDialog.java:240)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.<init>(XDebuggerEvaluationDialog.java:148)
	at com.intellij.xdebugger.impl.actions.handlers.XDebuggerEvaluateActionHandler.a(XDebuggerEvaluateActionHandler.java:119)
	at com.intellij.xdebugger.impl.actions.handlers.XDebuggerEvaluateActionHandler.perform(XDebuggerEvaluateActionHandler.java:97)
	at com.intellij.xdebugger.impl.actions.handlers.XDebuggerActionHandler.perform(XDebuggerActionHandler.java:34)
	at com.intellij.xdebugger.impl.actions.XDebuggerActionBase.b(XDebuggerActionBase.java:99)
	at com.intellij.xdebugger.impl.actions.XDebuggerActionBase.performWithHandler(XDebuggerActionBase.java:91)
	at com.intellij.xdebugger.impl.actions.XDebuggerActionBase.actionPerformed(XDebuggerActionBase.java:80)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:617)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

```
null
```

**Comment by JesusFreke** [comment] 2016-02-27 21:12
Duplicate of #370

**Closed by JesusFreke** 2016-02-27 21:12 UTC
