### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#338] opened 2015-10-23 10:06 UTC
protocol.version: 1
os.name: Mac OS X
java.version: 1.8.0_25
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-141.1010
app.version.major: 14
app.version.minor: 1.3
app.build.date: 1431360000000
app.build.date.release: 1427040000000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.02
last.action: null
previous.exception: null
assignee.id: null

```
com.intellij.util.IncorrectOperationException: Incorrect type 'com.tencent.karaoke.module.songedit.ui.do' (JDK_1_8)
	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createTypeElementFromText(PsiJavaParserFacadeImpl.java:268)
	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createTypeInner(PsiJavaParserFacadeImpl.java:277)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createTypeFromText(PsiElementFactoryImpl.java:708)
	at org.jf.smalidea.psi.impl.SmaliMethodParameter.getType(SmaliMethodParameter.java:87)
	at com.intellij.psi.util.MethodSignatureBackedByPsiMethod.create(MethodSignatureBackedByPsiMethod.java:88)
	at com.intellij.psi.util.MethodSignatureBackedByPsiMethod.create(MethodSignatureBackedByPsiMethod.java:71)
	at org.jf.smalidea.psi.impl.SmaliMethod.getSignature(SmaliMethod.java:191)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:131)
	at com.intellij.psi.impl.PsiClassImplUtil.findMethodBySignature(PsiClassImplUtil.java:101)
	at org.jf.smalidea.psi.impl.SmaliClass.findMethodBySignature(SmaliClass.java:216)
	at org.jf.smalidea.psi.impl.SmaliMethodReference.resolve(SmaliMethodReference.java:160)
	at org.jf.smalidea.psi.impl.SmaliMethodReference.isReferenceTo(SmaliMethodReference.java:168)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:50)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$17.execute(PsiSearchHelperImpl.java:765)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.a(LowLevelSearchUtil.java:126)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:200)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3$1.compute(PsiSearchHelperImpl.java:214)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3$1.compute(PsiSearchHelperImpl.java:211)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.process(PsiSearchHelperImpl.java:211)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.process(PsiSearchHelperImpl.java:208)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$16.process(PsiSearchHelperImpl.java:729)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$16.process(PsiSearchHelperImpl.java:723)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$7.compute(PsiSearchHelperImpl.java:371)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$7.compute(PsiSearchHelperImpl.java:356)
	at com.intellij.openapi.application.ex.ApplicationUtil$1.run(ApplicationUtil.java:37)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:34)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.a(PsiSearchHelperImpl.java:356)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.access$000(PsiSearchHelperImpl.java:68)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$4.process(PsiSearchHelperImpl.java:304)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$4.process(PsiSearchHelperImpl.java:299)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:211)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:140)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:211)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:140)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

```

```
Incorrect type 'com.tencent.karaoke.module.songedit.ui.do' (JDK_1_8)
```

**Comment by JesusFreke** [comment] 2016-02-27 21:17
Duplicate of #342

**Closed by JesusFreke** 2016-02-27 21:17 UTC
