### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#468] opened 2016-11-02 16:39 UTC
protocol.version: 1
os.name: Mac OS X
java.version: 1.8.0_76-release
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-143.2370
app.version.major: 15
app.version.minor: 0.6
app.build.date: 1461780000000
app.build.date.release: 1446400800000
app.compilation.timestamp: null
update.channel.status: milestone
update.ignored.builds: 145.258
plugin.name: Smalidea
plugin.version: 0.02
last.action: FindUsages
previous.exception: null
assignee.id: null

```
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1055)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:661)
	at com.intellij.psi.impl.source.PsiFileImpl.getStub(PsiFileImpl.java:654)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.getPackageName(PsiJavaFileBaseImpl.java:95)
	at com.intellij.psi.impl.PsiClassImplUtil.getClassUseScope(PsiClassImplUtil.java:314)
	at com.intellij.psi.impl.source.PsiClassImpl.getUseScope(PsiClassImpl.java:648)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.getUseScope(PsiSearchHelperImpl.java:78)
	at com.intellij.psi.search.searches.ReferencesSearch$SearchParameters.getEffectiveSearchScope(ReferencesSearch.java:107)
	at org.jf.smalidea.findUsages.SmaliClassReferenceSearcher.processQuery(SmaliClassReferenceSearcher.java:75)
	at org.jf.smalidea.findUsages.SmaliClassReferenceSearcher.processQuery(SmaliClassReferenceSearcher.java:51)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.find.findUsages.JavaFindUsagesHelper.b(JavaFindUsagesHelper.java:608)
	at com.intellij.find.findUsages.JavaFindUsagesHelper.processElementUsages(JavaFindUsagesHelper.java:139)
	at com.intellij.find.findUsages.JavaFindUsagesHandler.processElementUsages(JavaFindUsagesHandler.java:222)
	at com.intellij.find.findUsages.FindUsagesManager$2.generate(FindUsagesManager.java:376)
	at com.intellij.usages.impl.SearchForUsagesRunnable.searchUsages(SearchForUsagesRunnable.java:346)
	at com.intellij.usages.impl.SearchForUsagesRunnable.run(SearchForUsagesRunnable.java:325)
	at com.intellij.usages.impl.UsageViewManagerImpl$1.run(UsageViewManagerImpl.java:131)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

```

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 6,4,Idea Thread Group] 257093732
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 IDEA 15.0.6#IU-143.2370.31 IDEA, eap:false, os:Mac OS X 10.12.1, java-version:JetBrains s.r.o 1.8.0_76-release-b162,6,main] 1610993824
```

**Comment by JesusFreke** [comment] 2017-03-11 21:02
Duplicate of https://github.com/JesusFreke/smali/issues/335

**Closed by JesusFreke** 2017-03-11 21:02 UTC
