### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#328] opened 2015-10-23 03:00 UTC
protocol.version: 1
os.name: Windows 7
java.version: 1.8.0_51
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-141.2735
app.version.major: 14
app.version.minor: 1.5
app.build.date: 1442851200000
app.build.date.release: 1427040000000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.02
last.action: StepOver
previous.exception: null
assignee.id: null

```
java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:504)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:496)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:479)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:134)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:323)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:93)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createCodeFragment(SmaliCodeFragmentFactory.java:67)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createCodeFragment(CodeFragmentFactoryContextWrapper.java:56)
	at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor.createCodeFragment(EvaluationDescriptor.java:70)
	at com.intellij.debugger.ui.impl.watch.WatchItemDescriptor.getEvaluationCode(WatchItemDescriptor.java:86)
	at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor$1.compute(EvaluationDescriptor.java:85)
	at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor$1.compute(EvaluationDescriptor.java:82)
	at com.intellij.debugger.DebuggerInvocationUtil$3.compute(DebuggerInvocationUtil.java:76)
	at com.intellij.psi.impl.PsiDocumentManagerBase$6.run(PsiDocumentManagerBase.java:390)
	at com.intellij.psi.impl.PsiDocumentManagerBase$7.run(PsiDocumentManagerBase.java:422)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:417)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:387)
	at com.intellij.debugger.DebuggerInvocationUtil.commitAndRunReadAction(DebuggerInvocationUtil.java:72)
	at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor.calcValue(EvaluationDescriptor.java:82)
	at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.setContext(ValueDescriptorImpl.java:188)
	at com.intellij.debugger.engine.JavaDebuggerEvaluator$1.threadAction(JavaDebuggerEvaluator.java:89)
	at com.intellij.debugger.engine.events.DebuggerContextCommandImpl.contextAction(DebuggerContextCommandImpl.java:59)
	at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.a(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

```

```
null
```

**Comment by JesusFreke** [comment] 2016-02-27 21:21
Duplicate of #370

**Closed by JesusFreke** 2016-02-27 21:21 UTC
