### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#322] opened 2015-10-19 10:01 UTC
protocol.version: 1
os.name: Mac OS X
java.version: 1.8.0_25
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-141.1010
app.version.major: 14
app.version.minor: 1.3
app.build.date: 1431360000000
app.build.date.release: 1427040000000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.02
last.action: null
previous.exception: null
assignee.id: null

```
java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:504)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:496)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:479)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:134)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:323)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:93)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:77)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:60)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:75)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:45)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:228)
	at com.intellij.xdebugger.impl.ui.XDebuggerMultilineEditor.<init>(XDebuggerMultilineEditor.java:49)
	at com.intellij.xdebugger.impl.evaluate.CodeFragmentInputComponent.<init>(CodeFragmentInputComponent.java:45)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.b(XDebuggerEvaluationDialog.java:261)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.a(XDebuggerEvaluationDialog.java:234)
	at com.intellij.xdebugger.impl.evaluate.XDebuggerEvaluationDialog.<init>(XDebuggerEvaluationDialog.java:142)
	at com.intellij.xdebugger.impl.actions.handlers.XDebuggerEvaluateActionHandler.perform(XDebuggerEvaluateActionHandler.java:93)
	at com.intellij.xdebugger.impl.actions.handlers.XDebuggerActionHandler.perform(XDebuggerActionHandler.java:34)
	at com.intellij.xdebugger.impl.actions.XDebuggerActionBase.b(XDebuggerActionBase.java:98)
	at com.intellij.xdebugger.impl.actions.XDebuggerActionBase.performWithHandler(XDebuggerActionBase.java:90)
	at com.intellij.xdebugger.impl.actions.XDebuggerActionBase.actionPerformed(XDebuggerActionBase.java:78)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

```
null
```

**Comment by JesusFreke** [comment] 2016-02-27 21:24
Duplicate of #370

**Closed by JesusFreke** 2016-02-27 21:24 UTC
