### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#348] opened 2015-11-08 13:56 UTC
protocol.version: 1
os.name: Mac OS X
java.version: 1.8.0_40-release
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-143.381
app.version.major: 15
app.version.minor: 0
app.build.date: 1446134400000
app.build.date.release: 1446393600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.02
last.action: XDebugger.NewWatch
previous.exception: null
assignee.id: null

```
java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:504)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:496)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:479)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:134)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:323)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:93)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:77)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:60)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:75)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:45)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:240)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox$1.setItem(XDebuggerExpressionComboBox.java:100)
	at com.intellij.openapi.ui.ComboBox$MyEditor.setItem(ComboBox.java:376)
	at javax.swing.JComboBox.configureEditor(JComboBox.java:1404)
	at javax.swing.plaf.basic.BasicComboBoxUI.configureEditor(BasicComboBoxUI.java:787)
	at javax.swing.plaf.basic.BasicComboBoxUI.addEditor(BasicComboBoxUI.java:736)
	at javax.swing.plaf.basic.BasicComboBoxUI$Handler.propertyChange(BasicComboBoxUI.java:1710)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8440)
	at javax.swing.JComboBox.setEditor(JComboBox.java:506)
	at com.intellij.openapi.ui.ComboBox.setEditor(ComboBox.java:259)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.b(XDebuggerExpressionComboBox.java:110)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.<init>(XDebuggerExpressionComboBox.java:56)
	at com.intellij.xdebugger.impl.ui.tree.XDebuggerTreeInplaceEditor.<init>(XDebuggerTreeInplaceEditor.java:39)
	at com.intellij.xdebugger.impl.frame.WatchInplaceEditor.<init>(WatchInplaceEditor.java:46)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.editWatch(WatchesRootNode.java:212)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.addNewWatch(WatchesRootNode.java:197)
	at com.intellij.xdebugger.impl.frame.actions.XNewWatchAction.perform(XNewWatchAction.java:34)
	at com.intellij.xdebugger.impl.frame.actions.XWatchesTreeActionBase.actionPerformed(XWatchesTreeActionBase.java:60)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6543)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6308)
	at java.awt.Container.processEvent(Container.java:2235)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2293)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461)
	at java.awt.Container.dispatchEventImpl(Container.java:2279)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

```
null
```

**Comment by JesusFreke** [comment] 2016-02-27 21:15
duplicate of #370

**Closed by JesusFreke** 2016-02-27 21:15 UTC
