### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#341] opened 2015-10-27 06:24 UTC
protocol.version: 1
os.name: Mac OS X
java.version: 1.8.0_25
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-141.2735
app.version.major: 14
app.version.minor: 1.5
app.build.date: 1442851200000
app.build.date.release: 1427040000000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.02
last.action: null
previous.exception: null
assignee.id: null

```
com.intellij.util.IncorrectOperationException: Incorrect type 'com.tencent.karaoke.module.songedit.ui.do' (JDK_1_8)
	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createTypeElementFromText(PsiJavaParserFacadeImpl.java:268)
	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createTypeInner(PsiJavaParserFacadeImpl.java:277)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createTypeFromText(PsiElementFactoryImpl.java:708)
	at org.jf.smalidea.psi.impl.SmaliMethodParameter.getType(SmaliMethodParameter.java:87)
	at com.intellij.psi.util.MethodSignatureBackedByPsiMethod.create(MethodSignatureBackedByPsiMethod.java:88)
	at com.intellij.psi.util.MethodSignatureBackedByPsiMethod.create(MethodSignatureBackedByPsiMethod.java:71)
	at org.jf.smalidea.psi.impl.SmaliMethod.getSignature(SmaliMethod.java:191)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:131)
	at com.intellij.psi.impl.PsiClassImplUtil.findMethodBySignature(PsiClassImplUtil.java:101)
	at org.jf.smalidea.psi.impl.SmaliClass.findMethodBySignature(SmaliClass.java:216)
	at org.jf.smalidea.psi.impl.SmaliMethodReference.resolve(SmaliMethodReference.java:160)
	at org.jf.smalidea.psi.impl.SmaliMethodReference.isReferenceTo(SmaliMethodReference.java:168)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:50)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$14.execute(PsiSearchHelperImpl.java:739)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.a(LowLevelSearchUtil.java:129)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.access$000(LowLevelSearchUtil.java:42)
	at com.intellij.psi.impl.search.LowLevelSearchUtil$1.execute(LowLevelSearchUtil.java:199)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTextOccurrences(LowLevelSearchUtil.java:242)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:195)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2$1.compute(PsiSearchHelperImpl.java:211)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2$1.compute(PsiSearchHelperImpl.java:208)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.process(PsiSearchHelperImpl.java:208)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.process(PsiSearchHelperImpl.java:205)
	at com.intellij.concurrency.JobLauncherImpl$2$1.run(JobLauncherImpl.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.JobLauncherImpl$2.run(JobLauncherImpl.java:138)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.JobLauncherImpl.a(JobLauncherImpl.java:154)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:92)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processElementsWithWord(PsiSearchHelperImpl.java:186)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.b(PsiSearchHelperImpl.java:914)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:598)
	at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:84)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:78)
	at com.intellij.find.findUsages.FindUsagesHandler.findReferencesToHighlight(FindUsagesHandler.java:174)
	at com.intellij.find.findUsages.JavaFindUsagesHandler.findReferencesToHighlight(JavaFindUsagesHandler.java:245)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getHighlightUsages(IdentifierHighlighterPass.java:138)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.a(IdentifierHighlighterPass.java:167)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:204)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

```

```
Incorrect type 'com.tencent.karaoke.module.songedit.ui.do' (JDK_1_8)
```

**Comment by JesusFreke** [comment] 2016-02-27 21:17
Duplicate of #342

**Closed by JesusFreke** 2016-02-27 21:17 UTC
