### ISSUE TITLE
Smalidea not support in Android Studio 4.1

### ISSUE THREAD

**Issue by luffynas** [JesusFreke/smali#792] opened 2020-12-06 21:12 UTC
Android Studio version 4.1.1 error message (Incompatible only in Intellij IDEA) after install plugin Smalidea

i have been upgrade Android Studio version 4.1.1 from 4.0, at Android Studio 4.0 Smalidea plugin is fine.

<img width="398" alt="Screen Shot 2020-12-08 at 12 13 56" src="https://user-images.githubusercontent.com/4924973/101442949-e492f280-394e-11eb-84bd-93aea5931963.png">

**Comment by JesusFreke** [comment] 2020-12-06 22:02
No details provided

**Comment by luffynas** [comment] 2020-12-08 05:16
i have update detail for this issue

**Comment by Alexkaer** [comment] 2021-01-14 10:11
anyupdate about this issue, we cant use this plugin on AndroidStudio 4.1 now.  can u help to check,  thanks for you efforts.

**Comment by Alexkaer** [comment] 2021-01-14 10:13
the  error message is "Error : Could not find plugin descriptor while Installing plugin ..."

**Comment by SBBTD** [comment] 2021-01-18 11:33
Android Studio 4.1.1
smalidea 0.0.5
Event Log:
```
Plugin Error: Plugin "Smalidea" is incompatible (supported only in IntelliJ IDEA).
```

**Comment by cemian** [comment] 2021-01-25 12:55
I also encountered the same problem, how can I solve it?

**Comment by xiaodingding-sudo** [comment] 2021-02-09 04:31
+1

**Comment by xiaodingding-sudo** [comment] 2021-02-09 04:32
How to do this problem

**Comment by li-zhixin** [comment] 2021-02-12 03:59
+1

**Comment by JesusFreke** [comment] 2021-03-03 19:47
duplicate of https://github.com/JesusFreke/smalidea/issues/9

This should be working with v0.06 of the plugin.

**Closed by JesusFreke** 2021-03-03 19:47 UTC
