### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#495] opened 2017-03-06 09:00 UTC
protocol.version: 1
os.name: Mac OS X
java.version: 1.8.0_112-release
java.vm.vendor: JetBrains s.r.o
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-163.7743.44
app.version.major: 2016
app.version.minor: 3
app.build.date: 1479416496992
app.build.date.release: 1479772836992
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.02
last.action: null
previous.exception: null
assignee.id: null

```
java.lang.NoSuchMethodError: org.jf.smalidea.psi.impl.SmaliImplementsList.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
	at org.jf.smalidea.psi.impl.SmaliImplementsList.getImplementsElements(SmaliImplementsList.java:59)
	at org.jf.smalidea.psi.impl.SmaliImplementsList.getReferenceElements(SmaliImplementsList.java:53)
	at org.jf.smalidea.psi.impl.SmaliBaseReferenceList.getReferenceNames(SmaliBaseReferenceList.java:74)
	at org.jf.smalidea.psi.stub.element.SmaliImplementsListElementType.createStub(SmaliImplementsListElementType.java:65)
	at org.jf.smalidea.psi.stub.element.SmaliImplementsListElementType.createStub(SmaliImplementsListElementType.java:40)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.a(DefaultStubBuilder.java:113)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:88)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:83)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:58)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:39)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.a(StubTreeLoaderImpl.java:61)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:61)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:716)
	at com.intellij.psi.impl.source.PsiFileImpl.getStub(PsiFileImpl.java:681)
	at org.jf.smalidea.psi.impl.SmaliFile.getPsiClass(SmaliFile.java:57)
	at org.jf.smalidea.psi.impl.SmaliFile.getClasses(SmaliFile.java:71)
	at org.jf.smalidea.psi.impl.SmaliFile.getClasses(SmaliFile.java:46)
	at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider$1.compute(ClassesTreeStructureProvider.java:81)
	at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider$1.compute(ClassesTreeStructureProvider.java:77)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider.modify(ClassesTreeStructureProvider.java:77)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:53)
	at com.intellij.ide.util.treeView.AbstractTreeUi$31.perform(AbstractTreeUi.java:1617)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1835)
	at com.intellij.ide.util.treeView.AbstractTreeUi.getChildrenFor(AbstractTreeUi.java:1614)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$4500(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$30.perform(AbstractTreeUi.java:1539)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1835)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processUnbuilt(AbstractTreeUi.java:1521)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1244)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2900(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$25$1.perform(AbstractTreeUi.java:1167)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1835)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$25.perform(AbstractTreeUi.java:1164)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1159)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateSubtreeNow(AbstractTreeUi.java:1068)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater$3.perform(AbstractTreeUpdater.java:258)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:254)
	at com.intellij.ide.util.treeView.AbstractTreeUi$13.perform(AbstractTreeUi.java:498)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doExpandNodeChildren(AbstractTreeUi.java:494)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.expandNodeChildren(AbstractTreeBuilder.java:347)
	at com.intellij.ide.projectView.BaseProjectTreeBuilder.expandNodeChildren(BaseProjectTreeBuilder.java:110)
	at com.intellij.ide.util.treeView.AbstractTreeUi$MyExpansionListener.treeExpanded(AbstractTreeUi.java:4787)
	at javax.swing.JTree.fireTreeExpanded(JTree.java:2775)
	at javax.swing.JTree.setExpandedState(JTree.java:3629)
	at javax.swing.JTree.expandPath(JTree.java:2212)
	at com.intellij.ide.util.treeView.AbstractTreeUi$52.perform(AbstractTreeUi.java:3262)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.UpdaterTreeState.process(UpdaterTreeState.java:123)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processInnerChange(AbstractTreeUi.java:3283)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expandPath(AbstractTreeUi.java:3251)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1501)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1468)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExpand(AbstractTreeUi.java:4456)
	at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4392)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$8300(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$73.perform(AbstractTreeUi.java:4270)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expandNext(AbstractTreeUi.java:4284)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$8400(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$72.perform(AbstractTreeUi.java:4230)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1835)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4317)
	at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4204)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4194)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4189)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4185)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.expand(AbstractTreeBuilder.java:127)
	at com.intellij.ide.util.treeView.TreeState$BuilderFacade.expand(TreeState.java:480)
	at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:366)
	at com.intellij.ide.util.treeView.TreeState.access$500(TreeState.java:45)
	at com.intellij.ide.util.treeView.TreeState$3.perform(TreeState.java:377)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:366)
	at com.intellij.ide.util.treeView.TreeState.access$500(TreeState.java:45)
	at com.intellij.ide.util.treeView.TreeState$3.perform(TreeState.java:377)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:366)
	at com.intellij.ide.util.treeView.TreeState.access$500(TreeState.java:45)
	at com.intellij.ide.util.treeView.TreeState$3.perform(TreeState.java:377)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:366)
	at com.intellij.ide.util.treeView.TreeState.access$500(TreeState.java:45)
	at com.intellij.ide.util.treeView.TreeState$3.perform(TreeState.java:377)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:366)
	at com.intellij.ide.util.treeView.TreeState.access$500(TreeState.java:45)
	at com.intellij.ide.util.treeView.TreeState$3.perform(TreeState.java:377)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
	at com.intellij.openapi.util.ActionCallback$3.run(ActionCallback.java:275)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeUserRunnable(AbstractTreeUi.java:2539)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$UserRunnable.run(AbstractTreeBuilder.java:679)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1835)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4317)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5000(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$72$2.perform(AbstractTreeUi.java:4221)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
	at com.intellij.ide.util.treeView.AbstractTreeUi$73$1.perform(AbstractTreeUi.java:4273)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1835)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4317)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5000(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$76.onReady(AbstractTreeUi.java:4431)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processActions(AbstractTreeUi.java:2870)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processNodeActionsIfReady(AbstractTreeUi.java:2837)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExpand(AbstractTreeUi.java:4460)
	at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4392)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$8300(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$73.perform(AbstractTreeUi.java:4270)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expandNext(AbstractTreeUi.java:4284)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$8400(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$72.perform(AbstractTreeUi.java:4230)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.flushPendingNodeActions(AbstractTreeUi.java:2171)
	at com.intellij.ide.util.treeView.AbstractTreeUi.maybeYeildingFinished(AbstractTreeUi.java:2100)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2088)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5700(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$36$1.perform(AbstractTreeUi.java:1981)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:425)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2179)
	at com.intellij.ide.util.treeView.AbstractTreeUi$36.perform(AbstractTreeUi.java:1976)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.lambda$new$0(AbstractTreeBuilder.java:51)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

```
org.jf.smalidea.psi.impl.SmaliImplementsList.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
```

**Comment by JesusFreke** [comment] 2017-03-11 20:36
Duplicate of https://github.com/JesusFreke/smalidea-issues/issues/16

**Closed by JesusFreke** 2017-03-11 20:36 UTC
