### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#407] opened 2016-06-23 11:46 UTC
protocol.version: 1
os.name: Windows 8
java.version: 1.8.0_51
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: true
app.internal: false
app.build: IU-162.1024.1
app.version.major: 2016
app.version.minor: 2
app.build.date: 1466438400000
app.build.date.release: 1446393600000
app.compilation.timestamp: null
update.channel.status: eap
update.ignored.builds: 142.2491,142.2670,142.3050,142.3728,142.3926,142.4083,142.4245,142.4465,142.4675,142.4859,142.5047,142.5239,143.116,143.249,143.379,143.380,144.2151,144.2608,144.2925,144.3143,144.3357,144.3891,144.4199,145.184,145.256,145.257,145.258,145.596
plugin.name: Smalidea
plugin.version: 0.02
last.action: null
previous.exception: null
assignee.id: null

```
java.lang.NoSuchMethodError: org.jf.smalidea.psi.impl.SmaliImplementsList.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
	at org.jf.smalidea.psi.impl.SmaliImplementsList.getImplementsElements(SmaliImplementsList.java:59)
	at org.jf.smalidea.psi.impl.SmaliImplementsList.getReferenceElements(SmaliImplementsList.java:53)
	at org.jf.smalidea.psi.impl.SmaliBaseReferenceList.getReferenceNames(SmaliBaseReferenceList.java:74)
	at org.jf.smalidea.psi.stub.element.SmaliImplementsListElementType.createStub(SmaliImplementsListElementType.java:65)
	at org.jf.smalidea.psi.stub.element.SmaliImplementsListElementType.createStub(SmaliImplementsListElementType.java:40)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:74)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.a(StubUpdatingIndex.java:209)
	at com.intellij.psi.stubs.StubUpdatingIndex$4$$Lambda$607/1555206697.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:850)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:208)
	at com.intellij.psi.stubs.StubUpdatingIndex$4.map(StubUpdatingIndex.java:191)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:454)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1627)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1558)
	at com.intellij.util.indexing.FileBasedIndexImpl$$Lambda$606/880128415.run(Unknown Source)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:505)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1515)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1500)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:107)
	at com.intellij.util.indexing.UnindexedFilesUpdater$$Lambda$600/724381474.consume(Unknown Source)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:219)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$$Lambda$604/258696925.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1033)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:236)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$$Lambda$605/1145779830.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

```
Error while indexing F:\WorkSet\HH\gpstracker-android_2\GpsTracker\smali\android\support\v4\media\session\MediaSessionCompatApi22.smali
To reindex this file IDEA has to be restarted: org.jf.smalidea.psi.impl.SmaliImplementsList.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
```

**Comment by myzhan** [comment] 2016-08-22 07:56
Oops. I met the same problem, and IDEA reports

com.intellij.diagnostic.MessagePool$TooManyErrorsException: Too many IDE fatal errors. Monitoring stopped.

**Comment by JesusFreke** [comment] 2016-10-23 18:38
Duplicate of https://github.com/JesusFreke/smalidea-issues/issues/16

**Closed by JesusFreke** 2016-10-23 18:38 UTC
